### ISSUE TITLE
Figma. Общая структура

### ISSUE THREAD

**Issue by SkarabeyDM** [SkarabeyDM/graphiql-app#10]
## Application structure

- [x] Welcome page
- [x] User registration/authentication.
- [ ] RESTfull client, which includes:
   - [ ] method selector
   - [ ] text input for the endpoint url
   - [ ] request editor
   - [ ] headers editor
   - [ ] response section
- [ ] GraphiQL client, which includes:
   - [ ] text input for the endpoint url
   - [ ] request editor
   - [ ] variables editor
   - [ ] headers editor
   - [ ] text input for the endpoint which is used for getting the documentation (sdl)
   - [ ] documentation explorer
   - [ ] response section

**Comment by harmfuly** [comment]
[Structure](https://www.figma.com/design/4E33aycqj8gqmbBUZjHx1P/REST%2FGraphiQL-Client?node-id=16-71925)
