### ISSUE TITLE
Figma. Общие требования

### ISSUE THREAD

**Issue by SkarabeyDM** [SkarabeyDM/graphiql-app#3]
## Application design requirements

- [ ] the application quality is characterized by the elaboration of details, attention to typography (no more than three fonts per page, font size of at least 14 px, optimal [font and background contrast](https://snook.ca/technical/colour_contrast/colour.html)), carefully selected content
- [ ] interactivity of elements users can interact with; element hover effects; usage of different styles for the active and inactive state of the element; smooth animations
- [ ] the unity of styles of all pages of the application - the same fonts, button styles, indents, and the same elements on all pages of the application have the same appearance and layout. Item colors and background images may vary. In this case, colors should be from the same palette, and background images from the same collection.

### General requirements

- [ ] Errors (Not found route, unhandled rejection, etc) should be displayed in a user-friendly format (toast, pop-up, or something like that - up to your decision).
- [ ] Internationalization (i18n) - at least 2 languages. User should be able to change the language by clicking on the toggler/select in the header.

**Comment by harmfuly** [comment]
- Create Figma file
[Figma project](https://www.figma.com/design/4E33aycqj8gqmbBUZjHx1P/REST%2FGraphiQL-Client?m=auto&t=qFPLJSheK7DHyhLi-6)
- Add components from library Material UI
[Components](https://www.figma.com/design/4E33aycqj8gqmbBUZjHx1P/REST%2FGraphiQL-Client?node-id=0-1)
